[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.155.2"
  TZ = "America/Sao_Paulo"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --buildDrafts"

[context.branch-deploy]
  command = "hugo --gc --minify --buildFuture --buildDrafts"
